### PR TITLE
Allow publishCollection to run even if errors for single resources occur.

### PR DESCRIPTION
**Pull request by cwenzelg**
allow to continue the publication even if errors occur. To not run the full publication if there is a system error there is a option to only accept a limited amount of continues publication tries. The default settings is currently to 50 failure in a row before the complete collection publication get's aborted.

### CODE REVIEW

**Review by kdambekalns — COMMENTED** [review]
Wouldn't it be useful to have the limit per configured target, not for the whole GCS adaptor?

**Comment by kdambekalns** [comment]
Fellow contributors… how do we proceed here?

**Comment by cwenzelg** [comment]
I have no preferences there since never worked with multiple targets for one collection yet. not sure where it should be implemented there as the function only works with one target Bucket yet anyway? would it need to be implemented later on that the next collection continues even if this function gives an error?

**Comment by kdambekalns** [comment]
Closing this for now, feel free to re-open (and resolve conflicts) if needed. And maybe @robertlemke can chime in on this, still…

**Comment by cwenzelg** [comment]
@kdambekalns we can't use this package without the addition. there are hundreds of reasons why an image is in the db but might not be available anymore (visrus scan kicked it, storage failure etc.) and publication fails everthing after hours of progress to restart at 0 again. in a cloud setup it's crucial for us that not everything breaks if one image can't be copied. Why not implement this as is and if someone needs this based on targets as well we can add a new issue for that. right now it is file-based so the most detailed option.

**Comment by kdambekalns** [comment]
@cwenzelg Ok, so I assume you are using it from your fork, then?

**Comment by cwenzelg** [comment]
yeah, we are working with our fork right now. we also are in the progress of changing the version of flow so we would also have a look at this again. let me check if we can resolve the conflict, the next days.

**Comment by kdambekalns** [comment]
Hi @cwenzelg – it has again been a long time… So I finally wanted to resolve the conflict, and halfway through I wondered, if your change is actually still needed. Could you try with a current version? All errors are logged since https://github.com/flownative/flow-google-cloudstorage/commit/adb111055206d51f4aa662d14a2180286393ef84 (which is only a bit younger than when you created your branch…)

**Comment by cwenzelg** [comment]
@ariesprodesign do we even use this fix still or are we on a newer version and this issue is already fixed? do you know that? As i didn't touched code for quite a while, i don't know myself.

**Comment by paavo** [comment]
is this maybe related?
https://github.com/flownative/flow-google-cloudstorage/issues/17

**Comment by kdambekalns** [comment]
I checked the code again and close this as "already done."

**Pull request closed without merging**
