### PR TITLE
FEATURE: Use resumable uploads

### PR DESCRIPTION
**Pull request by kdambekalns**
This should lower the memory usage when storing into the cloud storage.

### CODE REVIEW

**Comment by kdambekalns** [comment]
Did not test that, but maybe it should work. :)

**Comment by robertlemke** [comment]
Now that we're running on the more modern SDK, there's an option for enabling resumable uploads. Let's look into that. Regarding chunked uploads, the SDK source code says that it's "not recommended to use". Well.

**Comment by kdambekalns** [comment]
Ok, then let's see what the new SDK achieves already.

**Pull request closed without merging**
